#!/usr/bin/python
def mainmenu():
    print "Content-type: text/html"
    print ""
    print "<html>"
    print "<title> JSE2 </title>"
    print "<head> <link rel=\"stylesheet\" href=\"/styles.css\"> </head> <body bgcolor=\"#3A332C\">"
    print "<center>"
    print "<h1><font color=\"#FFC300\"> JSE2 Projects Managment </font></h1>"
    print "<div class=\"menu5\">"
    print "<div class=\"dropdown\">"
    print "<a href=\"project.sh\">Projects</a>"
    print "<div class=\"dropdown-content\">"
    print "<a href=\"project-list.sh\">Project-list</a>"
    print "<a href=\"project-create.sh\">Project-create</a>"
    print "</div>"
    print "</div>"
    print "<div class=\"dropdown\">"
    print "<a href=\"project.sh\">Project-quota</a>"
    print "<div class=\"dropdown-content\">"
    print "<a href=\"project-list.sh\">Quota-check</a>"
    print "<a href=\"project-create.sh\">Quota-update</a>"
    print "</div>"
    print "</div>"
    print "<div class=\"dropdown\">"
    print "<a href=\"project.sh\">Users</a>"
    print "<div class=\"dropdown-content\">"
    print "<a href=\"user-list.sh\">Users-list</a>"
    print "<a href=\"user-create.sh\">User-Create</a>"
    print "</div>"
    print "</div>"
    print "<div class=\"dropdown\">"
    print "<a href=\"project.sh\">Groups</a>"
    print "<div class=\"dropdown-content\">"
    print "<a href=\"group-list.sh\">Group-list</a>"
    print "<a href=\"group-create.sh\">Group-Create</a>"
    print "</div>"
    print "</div>"
    print "<a href=\"group-project.sh\">Group-Project-Mapping</a>"
    print "<a href=\"user-group.sh\">User-Group-Mapping</a>"
    print "</div>"
mainmenu()
